Adds FFaker::Number:leading_zero_number
ffaker/ffaker pull request #538
Opened 2023-08-31 16:17 UTC by professor

I'm on a project that has used both Faker and FFaker for a long time. We're now standardizing on FFaker. For much of the code, I'm able to use FFaker API calls. Occasionally, I come across a concept that I'd like to see in FFaker, hence this PR.

This adds a FFaker::Number.leading_zero_number.

Note that this would return a string, not an integer. I'm not sure if that breaks any design constraints with FFaker (as compared to Faker). We only use it once, so I'm happy to inline the code in our app. I'm providing it here for anyone else transitioning from Faker to FFaker.

2023-09-01 02:22 UTC, marocchino commented on lib/ffaker/number.rb
> +      "0#{FFaker::Number.number(digits: digits -1)}"
how about? `"%0#{digits}d" % fetch_sample(0...10**(digits - 1))`

2023-09-01 02:23 UTC, marocchino commented on test/test_number.rb
> +    assert_match(/0\d{3}/, @tester.leading_zero_number(digits: 3).to_s)
```suggestion
    assert_match(/\A0\d{9}\z/, @tester.leading_zero_number.to_s)
    assert_match(/\A0\d{2}\z/, @tester.leading_zero_number(digits: 3).to_s)
```

2023-09-04 14:32 UTC, professor commented on lib/ffaker/number.rb
> +      "0#{FFaker::Number.number(digits: digits -1)}"
Thanks!

2023-09-05 00:53 UTC, marocchino approved these changes

2023-09-05 06:42 UTC, AlexWayfer reviewed
I don't understand the meaning of this method.

And I don't understand Faker motivation for:
* adding this;
* [deprecating this](https://github.com/faker-ruby/faker/pull/1516);
* [removing this](https://github.com/faker-ruby/faker/pull/510);
* [re-adding this](https://github.com/faker-ruby/faker/pull/1651).

Where are discussions, reasons?

I see this algorithm very strange and rare-case for me. What do you need it for? Why not a regular number? Why 10 digits is default? Why only one guaranteed zero?

2023-09-05 23:41 UTC, marocchino requested changes
I realized you don't add :leading_zero_number to assert_methods_are_deterministic.
please add it?

2023-09-06 03:00 UTC, professor commented
> I realized you don't add :leading_zero_number to assert_methods_are_deterministic.
please add it?

Fixed

2023-09-06 03:04 UTC, professor commented
> I don't understand the meaning of this method.

In many systems, there are number (invoice numbers, account numbers) where there are leading 0's before the random numbers. 

My code base currently only uses this once and instead of typing
```
FFaker::Number.leading_zero_number(digits: 9)
```
I could replace it with
```
"0{FFaker::Number.number(digits: 8)}"
```

2023-09-06 04:21 UTC, marocchino approved these changes

2023-09-06 08:04 UTC, AlexWayfer commented
> In many systems, there are number (invoice numbers, account numbers) where there are leading 0's before the random numbers.

Yeah, I don't understand why it starts with 0. Why not with 1, 9, 111? It seems very specific for me, I've never seen or done such thing. I could only saw something like a company has ranges, and invoices are incrementing, and it looks like `10004567`, and can be `10876543` later.

So… if there any reason for single leading zero, standard — I'd like to know. Public reference. If no, if it's something specific and unexplained — I'm against a dedicate such method in library and for in-place simple implementations (just add 1 character).

For me it seems like "let's add a method, which returns Lorem Ipsum, but  in downcase, instead of external downcase method call".

I hope you understand.

2023-09-07 16:22 UTC, closed without merging

2023-09-09 08:54 UTC, AlexWayfer commented
Oh… interesting. Yeah, I'm not familiar with this, being a younger man than these systems. If it's only the reason, I mean type of such data — then yes, I'm for not adding this as kind of outdated. It'd be strange to drop 4-years-old Ruby versions support, but support 30-years old data format, which can be implemented very simply by those who needed.